---
apiVersion: v1
kind: pod
metadata:
  name: pod-1
  labels:
    app: my-service
spec:
  containers:
   - name: nginx
     image: nginx
     imagePullPolicy: Always
     ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: my-service
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80

