apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    course: devops
    duration: 25hrs
spec:
  containers:
   - name: nginx
     image: nginx
     ports:
     - containerPort: 80
     env:
     - name: course
       value: devops
     - name: duration
       value: 25hrs

