apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: ngin
    image: nginx
    envFrom:
      - configMapRef:
            name: game-demo


















# apiVersion: v1
# kind: Pod
# metadata:
#   name: my-pod
#   labels:
#     course: devops
#     duration: 25hrs
# spec:
#   containers:
#    - name: nginx
#      image: nginx
#      ports:
#      - containerPort: 80
#      env:
#       - name: course
#         valueFrom:
#           configMapKeyRef:
#             name: game-demo  # The ConfigMap this value comes from.
#             key: course      # The key to fetch.
#       - name: duration
#         valueFrom:
#           configMapKeyRef:
#             name: game-demo
#             key: duration



# apiVersion: v1
# kind: Pod
# metadata:
#   name: label-pod
#   labels:
#     course: docker
#     duration: 25hr
#     trainer: siva
#   annotations:
#     org.docker.kubernetes.image.maintainer: siva
# spec:
#   containers:
#   - name: nginx
#     image: nginx





# apiVersion: v1
# kind: Pod
# metadata:
#   name: env
# spec:
#   containers:
#   - name: ngin
#     image: nginx
#     env:
#     - name: course
#       value: docker
#     - name: trainer
#       value: siva
#     - name: duration
#       value: 25hrs
#     - name: DB_HOST
#       value: db.admin.com
#     - name: username
#       value: sivakumar








