
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    course: devops
    duration: 25hrs
spec:
  containers:
   - name: nginx
     image: nginx
     ports:
     - containerPort: 80
     env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: game-demo  # The ConfigMap this value comes from.
            key: course      # The key to fetch.
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: game-demo
            key: duration

