apiVersion: v1
kind: pod
metadata:
 name: mutliple-pods
 namespace: roboshop
spec:
 containers:
  - name: nginx-2
    image: nginx
    Ports:
     - containerPort: 80
  - name: almalinux
    image: almalinux
    command: ["sleep","100"]