apiVersion: v1
kind: Pod
metadata:
  name: multiple-pods
  namespace: roboshop
spec:
  containers:
    - name: nginx-2
      image: nginx
      ports:
        - containerPort: 80
    - name: almalinux
      image: almalinux
      command: ["sleep", "100"]
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "250m" #how much a container can use
          memory: "100Mi"
        limits:
          cpu: "500m" #max limit a container can use
          memory: "250Mi"

               