apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
spec: 
 containers:
  - name: nginx
    image: nginx
    imagePullPolicy: always
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Awesome
    initialDelaySeconds: 3
    periodSeconds: 3 



# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-pod
# spec:
#   containers:
#     - name: nginx
#       image: nginx
#       ports:
#       - containerPort: 80