# apiVersion: v1
# kind: pod
# metadata:
#  name: nginx
# spec: 
#  containers:
#   - image: nginx
#     name: nginx
#     ports:
#     - containerPort: 80

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
