apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 14Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-pods
spec:
  containers:
  - name: my-nginx
    image: nginx:latest
    volumeMounts:
    - name: ebs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-claim
