apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::327858262904:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-Ogfn8GunB9wF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::327858262904:user/robo-shop
      username: robo-shop
    - userarn: arn:aws:iam::327858262904:user/ramesh
      username: ramesh
    - userarn: arn:aws:iam::327858262904:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n    - system:bootstrappers\n    - system:nodes\n  rolearn: arn:aws:iam::327858262904:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-Ogfn8GunB9wF\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::327858262904:user/robo-shop\n  username: robo-shop\n- userarn: arn:aws:iam::327858262904:user/ramesh\n  username: ramesh\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-02-17T08:45:17Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"6252","uid":"62699f62-192b-4c6a-879e-79070088125d"}}
  creationTimestamp: "2024-02-17T08:45:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "16453"
  uid: 62699f62-192b-4c6a-879e-79070088125d
