apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
  labels:
    name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: roboshop
  namespace: rbac
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop
  namespace: roboshop
subjects:
- kind: User
  name: robo-shop
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop
  apiGroup: rbac.authorization.k8s.io